// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljfwmvhptmynqfovsorw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqZndtdmhwdG15bnFmb3Zzb3J3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MTQyMTUsImV4cCI6MjA2NzM5MDIxNX0._DQvpoTnB12ils5H7EnAhV8xDVEGjxpQRioRDbwsEj4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});